### ISSUE TITLE
Move the order of the Tanks

### ISSUE THREAD

**Issue by naralon** [RostCS/DU-FuelScreen#1]
I was trying to change the order of the tanks on the screen because they don't match the order in my ship. Is there a way or a trick to do it? I already tried to connect them in a different order.

**Comment by RostCS** [comment]
If you're asking about the order of the tanks by type, currently it's hardcoded space->atmo->rocket. I can easily push an update later today however which allows you to customize that order.

If you're talking about the order of the tanks within the types, there is a trick to adjust the order. If you use build mode, right click, rename element on the tank you want listed first, and name it "Tank A", name the second tank "Tank B", and so on. It will put the tanks in alphabetical order.

I've yet to start working on the next update for the script, but I can make my next update be focused around being able to fully customize the order in an easy method

**Comment by naralon** [comment]
I was talking about the order within the types. That helped thx.
